expname: chest_all_360_mamba_2blocks
data:
  datadir: /media/viplab/DATADRIVE1/mednerf_drr_poses_pixelnerf/chest
  type: drr
  imsize: 128
  white_bkgd: False
  radius: 9.5,10.5
  near: 7.5
  far: 12.5
  fov: 10.
  umin: 0 # 0 deg
  umax: 1. # 360 deg
  vmin: 0.32898992833716556 # 70 deg
  vmax: 0.45642212862617093   # 85 deg
training:
  nworkers: 0
  mamba_blocks: 2
  batch_size: 8
  video_every: 1000
